#!/bin/bash
set -euo pipefail

################################################################################
# Mass Times Scraper Deploy Script
#
# Reads configuration from nwp.yml and .secrets.yml, generates mass-times.conf,
# and deploys the mass times scraper to the NWP GitLab server via rsync + SSH.
#
# Usage:
#   ./deploy-mass-times.sh              # Deploy and run setup on server
#   ./deploy-mass-times.sh --conf-only  # Just generate conf (no deploy)
#   ./deploy-mass-times.sh --help       # Show this help
#
# Prerequisites:
#   - yq installed locally (reads nwp.yml)
#   - SSH access to the NWP GitLab server
#   - nwp.yml configured with mass_times and settings sections
#
################################################################################

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NWP_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
NWP_YML="$NWP_DIR/nwp.yml"
SECRETS_YML="$NWP_DIR/.secrets.yml"
CONF_FILE="$SCRIPT_DIR/mass-times.conf"

source "$NWP_DIR/lib/ui.sh"

OPT_CONF_ONLY=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --conf-only) OPT_CONF_ONLY=true; shift ;;
        --help|-h) sed -n '2,17p' "$0" | sed 's/^# //' | sed 's/^#//'; exit 0 ;;
        *) print_error "Unknown option: $1"; exit 1 ;;
    esac
done

################################################################################
# Generate Configuration
################################################################################

generate_conf() {
    print_info "Reading configuration from nwp.yml..."

    if ! command -v yq &> /dev/null; then
        print_error "yq is required to read nwp.yml. Install: https://github.com/mikefarah/yq"
        return 1
    fi

    if [[ ! -f "$NWP_YML" ]]; then
        print_error "nwp.yml not found at $NWP_YML"
        return 1
    fi

    local admin_email email_domain ssh_host ssh_key timezone
    local centre_lat centre_lng radius_km shadow_mode
    local fallback_model max_monthly_llm_usd tier3_daily_limit
    local claude_api_key google_places_api_key drupal_api_password

    # Email and server settings (from settings section)
    admin_email=$(yq eval '.settings.email.admin_email // ""' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    email_domain=$(yq eval '.settings.email.domain // ""' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    ssh_host=$(yq eval '.linode.servers.nwpcode.ssh_host // ""' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    ssh_key=$(yq eval '.linode.servers.nwpcode.ssh_key // ""' "$NWP_YML" 2>/dev/null | grep -v '^null$')

    # Read timezone
    source "$NWP_DIR/lib/timezone.sh"
    timezone=$(get_default_timezone "$NWP_YML")

    # Mass times settings
    centre_lat=$(yq eval '.settings.mass_times.centre_lat // "-37.8131"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    centre_lng=$(yq eval '.settings.mass_times.centre_lng // "145.2285"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    radius_km=$(yq eval '.settings.mass_times.radius_km // "20"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    fallback_model=$(yq eval '.settings.mass_times.fallback_model // "claude-sonnet-4-5"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    max_monthly_llm_usd=$(yq eval '.settings.mass_times.max_monthly_llm_usd // "5"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    tier3_daily_limit=$(yq eval '.settings.mass_times.tier3_daily_limit // "10"' "$NWP_YML" 2>/dev/null | grep -v '^null$')
    shadow_mode=$(yq eval '.settings.mass_times.shadow_mode // "true"' "$NWP_YML" 2>/dev/null | grep -v '^null$')

    # Secrets (from .secrets.yml)
    claude_api_key=""
    google_places_api_key=""
    drupal_api_password=""
    if [[ -f "$SECRETS_YML" ]]; then
        claude_api_key=$(yq eval '.mass_times.claude_api_key // ""' "$SECRETS_YML" 2>/dev/null | grep -v '^null$' || true)
        google_places_api_key=$(yq eval '.mass_times.google_places_api_key // ""' "$SECRETS_YML" 2>/dev/null | grep -v '^null$' || true)
        drupal_api_password=$(yq eval '.mass_times.drupal_api_password // ""' "$SECRETS_YML" 2>/dev/null | grep -v '^null$' || true)
    fi

    if [[ -z "$admin_email" ]]; then
        print_error "settings.email.admin_email not set in nwp.yml"
        return 1
    fi

    if [[ -z "$email_domain" ]]; then
        print_error "settings.email.domain not set in nwp.yml"
        return 1
    fi

    if [[ -z "$ssh_host" ]]; then
        print_error "linode.servers.nwpcode.ssh_host not set in nwp.yml"
        return 1
    fi

    cat > "$CONF_FILE" << EOF
# Auto-generated by deploy-mass-times.sh from nwp.yml
# Do not edit manually - re-run deploy to regenerate
#
# Source: $NWP_YML
# Generated: $(date -Iseconds)

# Email configuration (from settings.email)
MT_EMAIL_RECIPIENTS="$admin_email"
MT_EMAIL_FROM="mass-times@$email_domain"

# Timezone (from settings.timezone)
MT_TIMEZONE="$timezone"

# Geographic scope (from settings.mass_times)
MT_CENTRE_LAT="$centre_lat"
MT_CENTRE_LNG="$centre_lng"
MT_RADIUS_KM="$radius_km"

# LLM settings (from settings.mass_times)
MT_FALLBACK_MODEL="$fallback_model"
MT_MAX_MONTHLY_LLM_USD="$max_monthly_llm_usd"
MT_TIER3_DAILY_LIMIT="$tier3_daily_limit"

# API keys (from .secrets.yml)
MT_CLAUDE_API_KEY="$claude_api_key"
MT_GOOGLE_PLACES_API_KEY="$google_places_api_key"
MT_DRUPAL_API_PASSWORD="$drupal_api_password"

# Drupal sync
MT_DRUPAL_SITE="mt"
MT_DRUPAL_API_USER="mass_times_bot"
MT_DRUPAL_BASE_URL="https://mt.$email_domain"
MT_SYNC_AFTER_EXTRACTION="true"

# Shadow mode (from settings.mass_times.shadow_mode)
MT_SHADOW_MODE="$shadow_mode"
EOF

    print_success "Generated $CONF_FILE"
    echo "  MT_EMAIL_RECIPIENTS=$admin_email"
    echo "  MT_EMAIL_FROM=mass-times@$email_domain"
    echo "  MT_TIMEZONE=$timezone"
    echo "  MT_RADIUS_KM=$radius_km"
    echo "  SSH target: $ssh_host (key: ${ssh_key:-~/.ssh/nwp})"

    # Export for use by deploy function
    export DEPLOY_SSH_HOST="$ssh_host"
    export DEPLOY_SSH_KEY="${ssh_key:-~/.ssh/nwp}"
}

################################################################################
# Deploy to Server
################################################################################

deploy() {
    local ssh_host="$DEPLOY_SSH_HOST"
    local ssh_key="$DEPLOY_SSH_KEY"

    # Expand ~ in ssh_key
    ssh_key="${ssh_key/#\~/$HOME}"

    print_info "Deploying to $ssh_host..."

    # Rsync mt directory (exclude generated/runtime files)
    rsync -avz -e "ssh -i $ssh_key" \
        --exclude='.venv' \
        --exclude='*.log' \
        --exclude='data/' \
        --exclude='__pycache__' \
        --exclude='.pytest_cache' \
        "$SCRIPT_DIR/" "${ssh_host}:~/mt/"

    # Rsync required NWP libraries
    rsync -avz -e "ssh -i $ssh_key" \
        "$NWP_DIR/lib/ui.sh" \
        "$NWP_DIR/lib/timezone.sh" \
        "${ssh_host}:~/lib/"

    rsync -avz -e "ssh -i $ssh_key" \
        "$NWP_DIR/scripts/notify-email.sh" \
        "$NWP_DIR/scripts/notify.sh" \
        "${ssh_host}:~/scripts/"

    print_success "Files deployed"

    # Run setup on server
    echo ""
    print_info "Running setup on server..."
    ssh -i "$ssh_key" "$ssh_host" "chmod +x ~/mt/*.sh && cd ~/mt && ./setup-mass-times.sh"

    print_success "Deployment complete"
}

################################################################################
# Main
################################################################################

generate_conf || exit 1

if ! $OPT_CONF_ONLY; then
    echo ""
    deploy
fi
