#!/bin/bash
set -euo pipefail

################################################################################
# Mass Times Scraper
#
# Code-first extraction of Catholic mass times from parish bulletins and
# websites within 20km of Ringwood, Melbourne.
#
# Usage: ./mass-times.sh [OPTIONS]
#
# Options:
#   --discover          Run parish discovery
#   --build [parish]    Build/rebuild extraction template
#   --extract           Run extraction cycle
#   --status            Show system status
#   --report            Generate summary report
#   --check             Dry run (no writes)
#   --help, -h          Show this help
#
# Configuration:
#   Reads mass-times.conf (generated by deploy-mass-times.sh from nwp.yml)
#   Requires Python venv with dependencies (set up via setup-mass-times.sh)
#
# Examples:
#   ./mass-times.sh --status             # System status
#   ./mass-times.sh --discover           # Discover parishes
#   ./mass-times.sh --extract            # Run extraction cycle
#   ./mass-times.sh --build sacred-heart # Build template for parish
#   ./mass-times.sh --check              # Dry run
################################################################################

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NWP_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"

################################################################################
# Source Required Libraries
################################################################################

source "$NWP_DIR/lib/ui.sh"

################################################################################
# Configuration
################################################################################

# Load config from mass-times.conf if present (generated by deploy from nwp.yml)
CONF_FILE="$SCRIPT_DIR/mass-times.conf"
[[ -f "$CONF_FILE" ]] && source "$CONF_FILE"

# Email (defaults used only if not set in conf or environment)
EMAIL_RECIPIENTS="${MT_EMAIL_RECIPIENTS:-${EMAIL_RECIPIENTS:-admin@example.com}}"
EMAIL_FROM="${MT_EMAIL_FROM:-mass-times@example.com}"

# Timezone
TIMEZONE="${MT_TIMEZONE:-${TIMEZONE:-Australia/Sydney}}"

# Python (use NWP's or system python)
PYTHON="${MT_PYTHON:-python3}"

# Paths
DATA_DIR="$SCRIPT_DIR/data"
TEMPLATES_DIR="$SCRIPT_DIR/templates"
LOG_FILE="$SCRIPT_DIR/mass-times.log"

################################################################################
# Logging
################################################################################

log() {
    local msg="[$(TZ=$TIMEZONE date '+%Y-%m-%d %H:%M:%S %Z')] $*"
    echo "$msg" >> "$LOG_FILE"
}

################################################################################
# Python Runner
################################################################################

run_python() {
    local module="$1"
    shift
    "$PYTHON" -m "$module" "$@"
}

run_src() {
    local script="$1"
    shift
    "$PYTHON" "$SCRIPT_DIR/src/$script" "$@"
}

################################################################################
# Commands
################################################################################

cmd_status() {
    print_header "Mass Times Scraper Status"

    # Check Python
    echo -n "Python: "
    if "$PYTHON" --version &>/dev/null 2>&1; then
        echo -e "${GREEN}OK${NC} ($("$PYTHON" --version 2>&1))"
    else
        echo -e "${RED}MISSING${NC}"
    fi

    # Check venv dependencies
    echo -n "Dependencies: "
    if "$PYTHON" -c "import httpx, bs4, pdfplumber" 2>/dev/null; then
        echo -e "${GREEN}OK${NC}"
    else
        echo -e "${RED}MISSING${NC} (run setup-mass-times.sh)"
    fi

    # Check templates
    echo -n "Templates: "
    local template_count=0
    if [[ -d "$TEMPLATES_DIR" ]]; then
        template_count=$(find "$TEMPLATES_DIR" -name "*.json" | wc -l)
    fi
    echo "$template_count parishes"

    # Check data
    echo -n "Bulletins: "
    local bulletin_count=0
    if [[ -d "$DATA_DIR/bulletins" ]]; then
        bulletin_count=$(find "$DATA_DIR/bulletins" -name "*.pdf" 2>/dev/null | wc -l)
    fi
    echo "$bulletin_count PDFs archived"

    echo -n "Pages: "
    local page_count=0
    if [[ -d "$DATA_DIR/pages" ]]; then
        page_count=$(find "$DATA_DIR/pages" -name "*.html" 2>/dev/null | wc -l)
    fi
    echo "$page_count HTML snapshots"

    # Check config
    echo ""
    echo -n "Configuration: "
    if [[ -f "$CONF_FILE" ]]; then
        echo -e "${GREEN}OK${NC} ($CONF_FILE)"
    else
        echo -e "${YELLOW}Not deployed${NC} (using defaults)"
    fi

    # Check parishes.json
    echo -n "Parishes: "
    if [[ -f "$DATA_DIR/parishes.json" ]]; then
        local parish_count
        parish_count=$("$PYTHON" -c "import json; print(len(json.load(open('$DATA_DIR/parishes.json'))))" 2>/dev/null || echo "?")
        echo "$parish_count discovered"
    else
        echo -e "${YELLOW}Not discovered yet${NC} (run --discover)"
    fi

    echo ""
}

cmd_discover() {
    local dry_run="${1:-}"
    print_header "Parish Discovery"
    log "Starting parish discovery"

    local args=""
    if [[ "$dry_run" == "--check" ]]; then
        args="--dry-run"
        print_info "Dry run mode — no data will be saved"
    fi

    run_src "run_discovery.py" $args

    log "Parish discovery complete"
}

cmd_build() {
    local parish="${1:-}"
    print_header "Template Building"

    if [[ -n "$parish" ]]; then
        print_info "Building template for: $parish"
        log "Building template for $parish"
        run_src "run_build.py" --parish "$parish"
    else
        print_info "Building templates for all parishes"
        log "Building templates for all parishes"
        run_src "run_build.py" --all
    fi

    log "Template building complete"
}

cmd_extract() {
    local dry_run="${1:-}"
    print_header "Extraction Cycle"
    log "Starting extraction cycle"

    local args=""
    if [[ "$dry_run" == "--check" ]]; then
        args="--dry-run"
        print_info "Dry run mode — no data will be saved or synced"
    fi

    # Shadow mode from config (MT_SHADOW_MODE env var, set by mass-times.conf)
    if [[ "${MT_SHADOW_MODE:-false}" == "true" ]]; then
        args="$args --shadow"
        print_info "Shadow mode — all results flagged as provisional"
    fi

    run_src "run_extract.py" $args

    log "Extraction cycle complete"
}

cmd_report() {
    print_header "Mass Times Report"
    run_src "run_report.py"
}

################################################################################
# Help
################################################################################

show_help() {
    sed -n '2,30p' "$0" | sed 's/^# //' | sed 's/^#//'
    exit 0
}

################################################################################
# Main
################################################################################

# Parse arguments
DRY_RUN=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --discover)
            shift
            cmd_discover "${1:-}"
            exit $?
            ;;
        --build)
            shift
            cmd_build "${1:-}"
            exit $?
            ;;
        --extract)
            shift
            cmd_extract "${1:-}"
            exit $?
            ;;
        --status)
            cmd_status
            exit 0
            ;;
        --report)
            cmd_report
            exit $?
            ;;
        --check)
            DRY_RUN="--check"
            shift
            ;;
        --help|-h)
            show_help
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            ;;
    esac
done

# Default action: show status
cmd_status
