#!/bin/bash
set -euo pipefail

################################################################################
# Mass Times Scraper Setup Script
#
# Sets up the mass times scraping system on the NWP GitLab server.
# Installs Python dependencies, configures cron jobs, and tests connectivity.
#
# Usage:
#   ./setup-mass-times.sh              # Full setup
#   ./setup-mass-times.sh --check      # Check current setup status
#   ./setup-mass-times.sh --uninstall  # Remove cron jobs
#   ./setup-mass-times.sh --help       # Show this help
#
# Prerequisites:
#   - NWP email infrastructure configured
#   - python3 available
#   - Internet access for pip packages
#
################################################################################

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NWP_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"

# Source NWP UI
source "$NWP_DIR/lib/ui.sh"

# Configuration
MONITOR_SCRIPT="$SCRIPT_DIR/mass-times.sh"
LOG_FILE="$SCRIPT_DIR/mass-times.log"
CRON_USER="${CRON_USER:-$(whoami)}"
VENV_DIR="$SCRIPT_DIR/.venv"

# Load timezone from mass-times.conf (generated by deploy from nwp.yml)
CONF_FILE="$SCRIPT_DIR/mass-times.conf"
[[ -f "$CONF_FILE" ]] && source "$CONF_FILE"
CRON_TIMEZONE="${MT_TIMEZONE:-${TIMEZONE:-Australia/Sydney}}"

# Options
OPT_CHECK=false
OPT_UNINSTALL=false

################################################################################
# Parse Arguments
################################################################################

show_help() {
    sed -n '2,17p' "$0" | sed 's/^# //' | sed 's/^#//'
    exit 0
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --check|-c)
            OPT_CHECK=true
            shift
            ;;
        --uninstall)
            OPT_UNINSTALL=true
            shift
            ;;
        --help|-h)
            show_help
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            ;;
    esac
done

################################################################################
# Check Status
################################################################################

check_setup() {
    print_header "Mass Times Scraper Setup Status"

    local issues=0

    # Python
    echo -n "Python3: "
    if command -v python3 &> /dev/null; then
        echo -e "${GREEN}OK${NC} ($(python3 --version 2>&1))"
    else
        echo -e "${RED}MISSING${NC}"
        issues=$((issues + 1))
    fi

    # Venv and dependencies
    echo -n "Virtual env: "
    if [[ -d "$VENV_DIR" ]]; then
        echo -e "${GREEN}OK${NC} ($VENV_DIR)"
    else
        echo -e "${RED}MISSING${NC}"
        issues=$((issues + 1))
    fi

    echo -n "Dependencies: "
    if [[ -d "$VENV_DIR" ]]; then
        if "$VENV_DIR/bin/python3" -c "import httpx, bs4, pdfplumber" 2>/dev/null; then
            echo -e "${GREEN}OK${NC}"
        else
            echo -e "${RED}NOT INSTALLED${NC} in venv"
            issues=$((issues + 1))
        fi
    else
        echo -e "${RED}NO VENV${NC}"
        issues=$((issues + 1))
    fi

    # Monitor script
    echo -n "Main script: "
    if [[ -x "$MONITOR_SCRIPT" ]]; then
        echo -e "${GREEN}OK${NC} ($MONITOR_SCRIPT)"
    else
        echo -e "${RED}NOT EXECUTABLE${NC}"
        issues=$((issues + 1))
    fi

    # Cron
    echo -n "Cron jobs: "
    local cron_count
    cron_count=$(crontab -l 2>/dev/null | grep -c "mass-times" || true)
    if [[ "$cron_count" -gt 0 ]]; then
        echo -e "${GREEN}OK${NC} ($cron_count entries)"
        crontab -l 2>/dev/null | grep "mass-times" | while read -r line; do
            echo "  $line"
        done
    else
        echo -e "${YELLOW}NOT CONFIGURED${NC}"
        issues=$((issues + 1))
    fi

    # Email (postfix)
    echo -n "Postfix: "
    if systemctl is-active postfix &> /dev/null 2>&1; then
        echo -e "${GREEN}RUNNING${NC}"
    elif command -v mail &> /dev/null; then
        echo -e "${YELLOW}mail command available${NC}"
    else
        echo -e "${RED}NOT AVAILABLE${NC}"
        issues=$((issues + 1))
    fi

    # Config
    echo -n "Config: "
    if [[ -f "$CONF_FILE" ]]; then
        echo -e "${GREEN}OK${NC} ($CONF_FILE)"
    else
        echo -e "${YELLOW}NOT DEPLOYED${NC} (using defaults)"
    fi

    echo ""
    if [[ $issues -eq 0 ]]; then
        print_success "All checks passed"
    else
        print_warning "$issues issue(s) found"
    fi

    return "$issues"
}

################################################################################
# Uninstall
################################################################################

uninstall() {
    print_header "Removing Mass Times Scraper Cron Jobs"

    crontab -l 2>/dev/null | grep -v "mass-times" | grep -v "^CRON_TZ=.*#.*mass-times" | crontab - 2>/dev/null || true
    print_success "Cron jobs removed"

    print_info "State files and logs preserved in $SCRIPT_DIR/"
    print_info "To fully remove: rm -rf $SCRIPT_DIR/.venv $SCRIPT_DIR/mass-times.log"
}

################################################################################
# Setup
################################################################################

setup() {
    print_header "Mass Times Scraper Setup"

    # 1. Python venv + dependencies
    echo ""
    print_info "Setting up Python environment..."

    if [[ ! -d "$VENV_DIR" ]]; then
        python3 -m venv "$VENV_DIR"
        print_status "OK" "Virtual environment created"
    else
        print_status "OK" "Virtual environment exists"
    fi

    "$VENV_DIR/bin/pip" install --quiet --upgrade pip
    "$VENV_DIR/bin/pip" install --quiet \
        httpx beautifulsoup4 pdfplumber geopy icalendar lxml pytest
    print_status "OK" "Core dependencies installed"

    # Optional: anthropic for Tier 3 LLM fallback
    "$VENV_DIR/bin/pip" install --quiet anthropic 2>/dev/null || true
    print_status "OK" "Optional LLM dependencies installed (anthropic)"

    # 2. Make scripts executable
    chmod +x "$MONITOR_SCRIPT"
    print_status "OK" "Main script is executable"

    # 3. Create wrapper that uses the venv python
    local wrapper="$SCRIPT_DIR/run-mass-times.sh"
    cat > "$wrapper" << EOF
#!/bin/bash
# Auto-generated wrapper that sets the correct Python for mass-times.sh
export MT_PYTHON="$VENV_DIR/bin/python3"
exec "$MONITOR_SCRIPT" "\$@"
EOF
    chmod +x "$wrapper"
    print_status "OK" "Wrapper script created: $wrapper"

    # 4. Create directories
    mkdir -p "$SCRIPT_DIR/data/bulletins" "$SCRIPT_DIR/data/pages" "$SCRIPT_DIR/templates"
    print_status "OK" "Data directories created"

    # 5. Set up cron jobs
    echo ""
    print_info "Configuring cron jobs..."

    # Remove existing mass-times entries
    crontab -l 2>/dev/null | grep -v "mass-times" | grep -v "^CRON_TZ=.*#.*mass-times" | crontab - 2>/dev/null || true

    # Add new entry — daily at 3am in configured timezone
    (crontab -l 2>/dev/null || true; cat << EOF
CRON_TZ=$CRON_TIMEZONE  # mass-times timezone
# Mass Times Scraper - 3am daily extraction
0 3 * * * $wrapper --extract >> $LOG_FILE 2>&1
EOF
    ) | crontab -

    print_status "OK" "Cron job installed"
    crontab -l | grep "mass-times" | while read -r line; do
        echo "  $line"
    done

    # 6. Test status
    echo ""
    print_info "Testing status..."
    if MT_PYTHON="$VENV_DIR/bin/python3" "$MONITOR_SCRIPT" --status; then
        print_status "OK" "Status check works"
    else
        print_warning "Status check failed"
    fi

    # 7. Summary
    echo ""
    print_header "Setup Complete"

    echo "Commands:"
    echo "  $wrapper --status          System status"
    echo "  $wrapper --discover        Discover parishes"
    echo "  $wrapper --build           Build templates"
    echo "  $wrapper --extract         Run extraction"
    echo "  $wrapper --check           Dry run"
    echo ""
    echo "Also available as:  pl mass-times [options]"
    echo ""
    echo "Logs:  tail -50 $LOG_FILE"
}

################################################################################
# Main
################################################################################

if $OPT_CHECK; then
    check_setup
elif $OPT_UNINSTALL; then
    uninstall
else
    setup
fi
