# Site Data Secrets Configuration
# ================================
# SECURITY WARNING: This file contains secrets that provide access to USER DATA.
# NEVER share this file or its contents with AI assistants (Claude, Copilot, etc.)
#
# Copy this file to .secrets.data.yml and fill in your values
# NEVER commit .secrets.data.yml to version control!
#
# For development/staging secrets, use .secrets.yml instead.

# === PRODUCTION DATABASE ===
# Direct access to production user data
production_database:
  host: ""
  port: 3306
  name: ""
  user: ""
  password: ""
  # Root/admin access (for migrations only)
  admin_user: "root"
  admin_password: ""

# === PRODUCTION SSH ===
# SSH access to production server with user data
production_ssh:
  key_path: ""                         # Path to SSH private key
  user: ""                             # SSH username
  host: ""                             # Production server
  port: 22
  remote_path: ""                      # Site path on server

# === PRODUCTION SMTP ===
# Email server that handles user communications
production_smtp:
  host: ""
  port: 587
  username: ""
  password: ""
  from_email: ""

# === DRUPAL ADMIN (Production) ===
# Production site admin credentials
production_drupal:
  admin_user: ""
  admin_password: ""
  admin_email: ""

# === PRODUCTION API KEYS ===
# API keys connected to production user data
production_services:
  sendgrid_key: ""                     # Production email
  stripe_secret: ""                    # Payment processing
  # Add other production service keys here

# === BACKUP ENCRYPTION ===
# Keys for encrypted backups
backup:
  encryption_key: ""                   # GPG or openssl passphrase
  b2_account_id: ""                    # Production backup storage
  b2_app_key: ""

# ============================================================================
# SECURITY NOTES
# ============================================================================
# 1. This file is blocked by Claude Code deny rules
# 2. Keep this file OFF development machines if possible
# 3. Consider using a secrets manager for production
# 4. Rotate all credentials every 90 days
# ============================================================================
