# NWP Data Secrets Configuration
# ================================
# SECURITY WARNING: This file contains secrets that provide access to USER DATA.
# NEVER share this file or its contents with AI assistants (Claude, Copilot, etc.)
#
# Copy this file to .secrets.data.yml and fill in your values
# NEVER commit .secrets.data.yml to version control!
#
# This file is separate from .secrets.yml (infrastructure secrets) by design.
# See docs/DATA_SECURITY_BEST_PRACTICES.md for the two-tier secrets architecture.

# === PRODUCTION SSH ACCESS ===
# SSH credentials that can access servers containing user data
# Keep these OFF your development machine if possible
production_ssh:
  # Primary production server
  primary:
    key_path: "keys/prod_deploy"      # Path to SSH private key
    user: "deploy"                     # SSH username
    host: ""                           # Production server hostname/IP
    port: 22                           # SSH port

  # Database server (if separate)
  database:
    key_path: "keys/prod_db"
    user: "dbadmin"
    host: ""
    port: 22

  # Backup server
  backup:
    key_path: "keys/prod_backup"
    user: "backup"
    host: ""
    port: 22

# === PRODUCTION DATABASE CREDENTIALS ===
# These credentials provide direct access to production user data
databases:
  production:
    host: ""                           # Database server hostname
    port: 3306                         # Database port
    name: ""                           # Database name
    admin_user: "root"                 # Admin username (for migrations)
    admin_password: ""                 # Admin password
    app_user: ""                       # Application username
    app_password: ""                   # Application password
    backup_user: ""                    # Backup username (read-only)
    backup_password: ""                # Backup password

  # Staging database (may contain sanitized prod data)
  staging:
    host: ""
    port: 3306
    name: ""
    admin_password: ""
    app_password: ""

# === GITLAB ADMIN CREDENTIALS ===
# Moved from .secrets.yml - these provide admin access to GitLab server
gitlab_admin:
  password: ""                         # GitLab root password
  ssh_key: ""                          # SSH key path for GitLab server access
  recovery_codes: []                   # 2FA recovery codes (if enabled)

# === PRODUCTION SMTP/EMAIL ===
# Email credentials that could expose user communications
smtp_production:
  host: ""                             # Production SMTP server
  port: 587
  username: ""
  password: ""
  from_email: ""
  # Transactional email service keys
  sendgrid_key: ""                     # Production SendGrid API key
  mailgun_key: ""                      # Production Mailgun API key

# === PRODUCTION API KEYS ===
# API keys that access production services with user data
production_apis:
  # Payment processing (if applicable)
  stripe_secret_key: ""                # Stripe secret key (NOT publishable)
  paypal_client_secret: ""

  # CRM/Marketing with user data
  mailchimp_key: ""                    # If connected to real user lists
  hubspot_key: ""

  # Analytics with user data
  google_analytics_key: ""             # If using User-ID tracking
  mixpanel_key: ""

# === ENCRYPTION KEYS ===
# Keys used to encrypt user data at rest
encryption:
  database_key: ""                     # Database field encryption key
  file_key: ""                         # File encryption key
  backup_key: ""                       # Backup encryption passphrase

# === ADMIN ACCOUNTS ===
# Production admin credentials
admin_accounts:
  drupal:
    username: ""
    password: ""
    email: ""

  moodle:
    username: ""
    password: ""
    email: ""

# === BACKUP STORAGE CREDENTIALS ===
# If backups contain unencrypted user data
backup_storage:
  # S3-compatible storage
  s3:
    access_key: ""
    secret_key: ""
    bucket: ""
    endpoint: ""

  # Backblaze B2 (production backups)
  b2_production:
    account_id: ""
    application_key: ""
    bucket_name: ""

# === NOTES ===
# 1. This file should NEVER be on a machine where Claude Code runs
# 2. Consider using a secrets manager (Vault, AWS Secrets Manager) instead
# 3. Production deployments should inject secrets via CI/CD, not this file
# 4. Rotate all credentials in this file every 90 days
# 5. If this file is compromised, rotate ALL credentials immediately
