# NWP Infrastructure Secrets Configuration
# =========================================
# This file contains INFRASTRUCTURE secrets only - API tokens for provisioning
# and managing services. These secrets do NOT provide access to user data.
#
# AI ASSISTANT SAFE: This file can be read by Claude Code and similar tools.
# The deny rules in ~/.claude/settings.json allow access to .secrets.yml
# but block .secrets.data.yml (which contains user data secrets).
#
# Copy this file to .secrets.yml and fill in your values
# NEVER commit .secrets.yml to version control!
#
# For secrets that access user data (database passwords, production SSH),
# see .secrets.data.example.yml instead.

# === LINODE API ===
# Used for server provisioning and management (no console/root access)
# Get your API token from: https://cloud.linode.com/profile/tokens
# RECOMMENDED: Create a scoped token with only:
#   - Linodes: Read/Write (create/resize servers)
#   - NO Lish console access (prevents data access)
linode:
  api_token: ""

# === CLOUDFLARE API ===
# Used for DNS management and CDN configuration
# Get your API token from: https://dash.cloudflare.com/profile/api-tokens
# RECOMMENDED: Create a Custom Token with only:
#   - Zone > DNS > Edit
#   - Zone > Zone > Read
cloudflare:
  api_token: ""
  zone_id: ""                          # From domain's Overview page

# === BACKBLAZE B2 (Development/Staging) ===
# Used for non-production backup storage and podcast media
# NOTE: Production backup credentials go in .secrets.data.yml
b2:
  account_id: ""
  app_key: ""

# === GITLAB SERVER (Infrastructure) ===
# API access for repository management
# NOTE: Admin password and SSH key moved to .secrets.data.yml
gitlab:
  server:
    domain: ""                         # e.g., git.yourdomain.org
    ip: ""                             # Server IP (for DNS setup)
    linode_id: ""                      # Linode instance ID
  api_token: ""                        # GitLab API token (repo access only)
  # Composer Package Registry URL for private packages
  # Format: https://git.<domain>/api/v4/group/<GROUP_ID>/-/packages/composer/packages.json
  # Get GROUP_ID: source lib/git.sh && gitlab_get_group_id "root"
  # See docs/GITLAB_COMPOSER.md for setup instructions
  composer_url: ""                     # Set after running ./setup.sh -> GitLab Composer Registry

# === GITHUB (Optional) ===
# For GitHub integrations and mirroring
github:
  api_token: ""                        # Personal access token

# === DEVELOPMENT DEFAULTS ===
# Used when creating LOCAL development sites only
# Production credentials go in .secrets.data.yml
dev_defaults:
  drupal:
    admin_user: admin
    admin_password: ""                 # Empty = generate random
    admin_email: admin@localhost

  moodle:
    admin_user: admin
    admin_password: ""                 # Empty = use default
    admin_email: admin@example.com

  # Local SMTP (for development mail testing)
  smtp:
    host: "localhost"
    port: 1025                         # Mailhog default
    username: ""
    password: ""

# === THIRD-PARTY SERVICES (Development Keys) ===
# Use development/sandbox API keys here
# Production keys go in .secrets.data.yml
services:
  # Development/sandbox keys only
  sendgrid_key: ""                     # Sandbox API key
  ga_tracking_id: ""                   # Test property ID

# === CLAUDE API (F14) ===
# Used for Claude API provisioning and workspace management
# See: https://console.anthropic.com/settings/keys
claude:
  org_api_key: ""              # Organization-level API key
  admin_api_key: ""            # Admin API key for workspace/usage management

# === CUSTOM INFRASTRUCTURE SECRETS ===
# Add infrastructure-related secrets here (API tokens, not passwords)
# custom:
#   terraform_token: ""
#   ansible_vault_pass: ""

# ============================================================================
# SECURITY ARCHITECTURE
# ============================================================================
#
# This file (.secrets.yml):
#   - API tokens for provisioning (Linode, Cloudflare, GitLab)
#   - Development/staging credentials
#   - CAN be read by AI assistants
#
# .secrets.data.yml (separate file):
#   - Production SSH keys
#   - Production database passwords
#   - Production SMTP credentials
#   - Encryption keys
#   - CANNOT be read by AI assistants
#
# See docs/DATA_SECURITY_BEST_PRACTICES.md for full documentation.
# ============================================================================
