# NWP Infrastructure Secrets Configuration
# Copy this file to .secrets.yml and add your actual credentials
# NEVER commit .secrets.yml to version control!

# Linode API Configuration
# Used for automatic SSH key deployment and server management
linode:
  # Get your API token from: https://cloud.linode.com/profile/tokens
  # Create a Personal Access Token with Linodes Read/Write permissions
  api_token: YOUR_LINODE_API_TOKEN_HERE

# Example: Additional infrastructure secrets can be added here
# github:
#   api_token: YOUR_GITHUB_TOKEN
#
# gitlab:
#   api_token: YOUR_GITLAB_TOKEN

# Note: Site-specific secrets (database passwords, etc.) should be stored in
# each site's .secrets.yml file (e.g., nwp5/.secrets.yml), not here.
# This file is for NWP infrastructure-level secrets only.
