# NWP Infrastructure Secrets Configuration
# Copy this file to .secrets.yml and fill in your values
# NEVER commit .secrets.yml to version control!

# === LINODE API ===
# Get your API token from: https://cloud.linode.com/profile/tokens
# Create a Personal Access Token with Linodes Read/Write permissions
linode:
  api_token: ""

# === CLOUDFLARE API ===
# Used for DNS management and CDN configuration
cloudflare:
  # Get your API token from: https://dash.cloudflare.com/profile/api-tokens
  # Create a Custom Token with permissions:
  #   - Zone > DNS > Edit
  #   - Zone > Zone > Read
  #   - Zone > Cache Purge > Purge (optional)
  #   - Zone > Zone Settings > Edit (optional)
  api_token: ""
  # Get Zone ID from your domain's Overview page in Cloudflare dashboard
  zone_id: ""

# === BACKBLAZE B2 ===
# Used for podcast media storage
b2:
  # Get credentials from: https://secure.backblaze.com/app_keys.htm
  # Use your master application key or create one with all capabilities
  account_id: ""
  app_key: ""

# === GITLAB SERVER ===
# Populated automatically when GitLab server is created
gitlab:
  server:
    domain: ""                     # e.g., git.yourdomain.org
    ip: ""                         # Server IP address
    linode_id: ""                  # Linode instance ID
    ssh_user: gitlab               # SSH username for server access
    ssh_key: ~/.ssh/gitlab         # Path to SSH private key
  api_token: ""                    # GitLab API token for project creation
  # Admin credentials (stored for reference, not actively read)
  # admin:
  #   username: root
  #   password: ""

# === DRUPAL DEFAULTS ===
# Used by install.sh when creating Drupal sites
# If empty, will use hardcoded defaults
drupal:
  admin_user: admin                # Drupal admin username
  admin_password: ""               # Empty = generate random password
  admin_email: admin@localhost     # Admin email address

# === MOODLE DEFAULTS ===
# Used by install.sh when creating Moodle sites
# If empty, will use hardcoded defaults
moodle:
  admin_user: admin                # Moodle admin username
  admin_password: ""               # Empty = use Admin123!
  admin_email: admin@example.com   # Admin email address
  shortname: moodle                # Site short name

# === SMTP CONFIGURATION ===
# For sites that need email functionality
smtp:
  host: ""                         # SMTP server hostname
  port: 587                        # SMTP port (usually 587 for TLS)
  username: ""                     # SMTP username
  password: ""                     # SMTP password
  from_email: ""                   # Default from email address

# === DEPLOYMENT DEFAULTS ===
# Default SSH settings for production deployments
# Per-server configs should go in cnwp.yml linode.servers section
deployment:
  ssh_key: ~/.ssh/id_rsa           # Default SSH private key
  ssh_user: ""                     # Default SSH username
  ssh_port: 22                     # Default SSH port

# === THIRD-PARTY SERVICES ===
# API keys for optional integrations
services:
  # Email services
  sendgrid_key: ""                 # SendGrid API key
  mailchimp_key: ""                # Mailchimp API key

  # Analytics
  ga_tracking_id: ""               # Google Analytics tracking ID

# === GITHUB (Optional) ===
# For GitHub integrations
# github:
#   api_token: ""                  # GitHub personal access token

# === CUSTOM SECRETS ===
# Add any project-specific secrets here
# custom:
#   my_api_key: ""
