server {
    listen 80;
    server_name ssc.nwpcode.org;
    return 301 https://ss.nwpcode.org$request_uri;
}
server {
    listen 443 ssl http2;
    server_name ssc.nwpcode.org;
    ssl_certificate /etc/letsencrypt/live/ssc.nwpcode.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ssc.nwpcode.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://ss.nwpcode.org$request_uri;
}
