# Site Secrets Configuration
# ===========================
# This file contains DEVELOPMENT/STAGING secrets for this site.
# These secrets do NOT provide access to production user data.
#
# AI ASSISTANT SAFE: This file can be read by Claude Code and similar tools.
#
# Copy this file to .secrets.yml and fill in your values
# NEVER commit .secrets.yml to version control!
#
# For production credentials, see .secrets.data.example.yml

# === API KEYS (Development/Sandbox) ===
api_keys:
  github_token: ""                     # For private repo access
  composer_auth: ""                    # Composer authentication

# === LOCAL DATABASE ===
# Credentials for local development database (ddev/lando manages these)
# Only fill in if using manual setup
database:
  host: "db"                           # ddev/lando container name
  port: 3306
  name: "db"
  user: "db"
  password: "db"

# === DRUPAL ADMIN (Development) ===
drupal:
  admin_user: "admin"
  admin_password: ""                   # Empty = generate random
  admin_email: "admin@localhost"

# === LOCAL SMTP ===
# For local mail testing (Mailhog, Mailpit)
smtp:
  host: "localhost"
  port: 1025
  username: ""
  password: ""
  from_email: "noreply@localhost"

# === STAGING DEPLOYMENT ===
# SSH settings for staging server (NOT production)
staging:
  ssh_key: "~/.ssh/id_rsa"
  ssh_user: ""
  ssh_host: ""
  ssh_port: 22
  remote_path: ""

# === THIRD-PARTY SERVICES (Sandbox Keys) ===
services:
  sendgrid_key: ""                     # Sandbox API key
  mailchimp_key: ""                    # Test list key
  ga_tracking_id: ""                   # Test property

# === CUSTOM SECRETS ===
# Add site-specific development secrets here
# custom:
#   my_dev_api_key: ""

# ============================================================================
# For PRODUCTION credentials (database, SSH, SMTP), use .secrets.data.yml
# See docs/DATA_SECURITY_BEST_PRACTICES.md for the security architecture
# ============================================================================
