# Secrets Configuration
# Copy this file to .secrets.yml in your site directory
# NEVER commit .secrets.yml to version control!

# Linode API Configuration
# Used for automatic SSH key deployment and server management
linode:
  # Get your API token from: https://cloud.linode.com/profile/tokens
  # Create a Personal Access Token with Linodes Read/Write permissions
  api_token: YOUR_LINODE_API_TOKEN_HERE

# Example: Additional infrastructure secrets can be added here
# github:
#   api_token: YOUR_GITHUB_TOKEN
#
# gitlab:
#   api_token: YOUR_GITLAB_TOKEN

# Note: Site-specific secrets (database passwords, etc.) should be stored in
# each site's .secrets.yml file (e.g., nwp5/.secrets.yml), not here.
# This file is for NWP infrastructure-level secrets only.

# API Keys and Tokens
api_keys:
  # GitHub personal access token
  github_token: ""

  # Acquia Cloud API credentials
  acquia_key: ""
  acquia_secret: ""

  # Composer authentication
  composer_auth: ""

# Database Credentials
database:
  # Admin/root password for database
  admin_password: ""

  # Backup database credentials
  backup_user: ""
  backup_password: ""

# Drupal Admin
drupal:
  # Drupal admin username
  admin_user: "admin"

  # Drupal admin password
  admin_password: ""

  # Drupal admin email
  admin_email: "admin@localhost"

# Email/SMTP Settings
smtp:
  host: ""
  port: 587
  username: ""
  password: ""
  from_email: ""

# Deployment
deployment:
  # SSH key path for deployment
  ssh_key: "~/.ssh/id_rsa"

  # SSH user for remote deployment
  ssh_user: ""

  # Remote host
  ssh_host: ""

  # Remote path
  remote_path: ""

# Third-party Services
services:
  # SendGrid API key
  sendgrid_key: ""

  # Mailchimp API key
  mailchimp_key: ""

  # Google Analytics
  ga_tracking_id: ""

  # Cloudflare
  cloudflare_api_key: ""
  cloudflare_zone_id: ""

# Custom secrets (add your own)
custom:
  # Add any custom secrets here
