#!/bin/bash
################################################################################
# lib/console-deploy.sh — divergence detection for `pl console deploy`
#
# WHY THIS EXISTS (a real near miss, 2026-07-25)
# ---------------------------------------------
# `pl console deploy` rsyncs with --delete. The console host was carrying an
# UNPUSHED local branch with the voice feature; a plain deploy would have
# silently destroyed it. Only a careful agent noticed and took a manual backup
# first. Automation must not depend on somebody being careful.
#
# So: before writing anything, compare what is ON the target with what is about
# to be deployed, and REFUSE fail-closed when the target holds work that the
# incoming change does not explain — files that only exist there (which
# --delete would destroy) or files edited there more recently than ours (which
# the copy would overwrite).
#
# Everything here is pure text processing over two manifests, so it is unit
# testable without a network: the only remote operation is producing the
# target's manifest.
#
# Manifest line format:   <sha256> <mtime-epoch> <relative-path>
################################################################################

# The manifest command, shared VERBATIM between local and remote so the two
# sides can never drift in what they count. Exclusions mirror the rsync
# --exclude list exactly; if they ever disagreed, generated bytecode on the
# target would look like divergence and refuse every deploy.
CONSOLE_MANIFEST_CMD='find . -type f \
  ! -path "*/__pycache__/*" ! -name "*.pyc" ! -name "*.pyo" \
  ! -path "*/.pytest_cache/*" ! -path "*/.git/*" \
  ! -name ".nwp-deployed.json" \
  -print | LC_ALL=C sort | while IFS= read -r f; do
    printf "%s %s %s\n" "$(sha256sum "$f" | cut -d" " -f1)" "$(stat -c %Y "$f")" "${f#./}"
  done'

# Produce a manifest for a local directory.
console_manifest_local() { # $1 dir
    local dir="$1"
    [ -d "$dir" ] || return 1
    ( cd "$dir" && eval "$CONSOLE_MANIFEST_CMD" )
}

# Classify target-vs-source. Prints one line per differing path:
#
#   A <path>   added    — not on the target yet (safe)
#   M <path>   modified — differs, ours is at least as new (the change itself)
#   ! <path>   MODIFIED ON TARGET — target's copy is newer; deploy would
#                                   overwrite work that exists only there
#   D <path>   DELETED  — exists only on the target; --delete would destroy it
#
# Exit: 0 = nothing that needs consent, 10 = divergence ('!' or 'D' present),
#       2 = a manifest could not be read.
#
# Note on the mtime test: rsync -a preserves times, so after a clean deploy the
# two sides match exactly. A target file that is NEWER than ours therefore means
# somebody changed it there — which is precisely the near miss.
console_deploy_classify() { # $1 local manifest, $2 target manifest
    local lm="$1" tm="$2"
    [ -r "$lm" ] && [ -r "$tm" ] || return 2
    LOCAL_MF="$lm" TARGET_MF="$tm" python3 - <<'PY'
import os, sys

def read(path):
    out = {}
    with open(path, "r", errors="replace") as f:
        for line in f:
            parts = line.rstrip("\n").split(" ", 2)
            if len(parts) != 3:
                continue
            sha, mtime, rel = parts
            try:
                mtime = float(mtime)
            except ValueError:
                continue
            out[rel] = (sha, mtime)
    return out

local = read(os.environ["LOCAL_MF"])
target = read(os.environ["TARGET_MF"])

lines, diverged = [], False
for rel in sorted(set(local) | set(target)):
    l, t = local.get(rel), target.get(rel)
    if l and not t:
        lines.append(("A", rel))
    elif t and not l:
        lines.append(("D", rel)); diverged = True     # --delete would destroy it
    elif l[0] != t[0]:
        # Same path, different content. Whose is newer decides whether this is
        # "the change we are deploying" or "work only the target has".
        if t[1] > l[1]:
            lines.append(("!", rel)); diverged = True
        else:
            lines.append(("M", rel))

for mark, rel in lines:
    print(f"{mark} {rel}")
sys.exit(10 if diverged else 0)
PY
}

# Human summary of a classification (stdin or $1 = classification file).
console_deploy_summary() { # $1 classification file
    CLASS_FILE="$1" python3 - <<'PY'
import os
from collections import Counter
counts = Counter()
rows = []
with open(os.environ["CLASS_FILE"], "r", errors="replace") as f:
    for line in f:
        line = line.rstrip("\n")
        if len(line) > 2:
            counts[line[0]] += 1
            rows.append(line)
label = {"A": "add", "M": "update", "!": "OVERWRITE (target is newer)", "D": "DELETE (only on target)"}
print("  {} add / {} update / {} overwrite-newer / {} delete".format(
    counts["A"], counts["M"], counts["!"], counts["D"]))
for mark in ("D", "!", "A", "M"):
    shown = [r for r in rows if r[0] == mark]
    for r in shown[:20]:
        print(f"    {r[0]}  {r[2:]}   [{label[mark]}]")
    if len(shown) > 20:
        print(f"    … and {len(shown) - 20} more {label[mark]}")
PY
}

# True when the classification contains anything requiring explicit consent.
console_deploy_has_divergence() { # $1 classification file
    grep -qE '^[!D] ' "$1"
}
