#!/usr/bin/env bash
# lib/server-host-guard.sh — is this box promiscuous about Host headers?
#
# nwp/ops#381. On 2026-08-19 an unrelated third party had a DANGLING A record
# pointing at a cloud address that had since been reallocated to our forge box,
# and aimed a commercial web-application vulnerability scanner at it. The scan
# landed on our GitLab, because GitLab's bundled nginx claims `default_server` on
# both ports and declares NO `server_name` at all:
#
#     /var/opt/gitlab/nginx/conf/service_conf/gitlab-rails.conf:35  listen *:80  default_server;
#     /var/opt/gitlab/nginx/conf/service_conf/gitlab-rails.conf:66  listen *:443 default_server ssl;
#
# So EVERY unmatched Host header was served the full application. 295,483
# requests / 2.1 GB on 19 Aug; 254,399 / 13.1 GB by 04:43 on 20 Aug, peaking near
# 20 Mb/s and tripping Linode's outbound traffic-RATE alarm (10 Mb/s threshold,
# 11.86 Mb/s observed).
#
# The dangling record was the trigger. The promiscuity is the defect, and it is
# ours: any hostname on earth pointed at that IP gets a GitLab to crawl, and the
# next one will not announce itself with a scanner's user-agent.
#
# THE FIX HAS A SEAT, AND IT IS NOT THE OBVIOUS ONE. GitLab's server block is
# generated by chef; editing /var/opt/gitlab/nginx/conf/ is silently reverted by
# the next `gitlab-ctl reconfigure`. The durable seat is `gitlab.rb`'s
# `nginx['custom_gitlab_server_config']`, which chef splices INTO that block.
#
# WHY A DENY-LIST OF ONE REGEX AND NOT A CATCH-ALL default_server: nginx permits
# exactly one `default_server` per listen address, and GitLab's block already
# claims it. Taking it away means editing chef-generated config — the thing we
# just said not to do. Guarding from inside the block sidesteps the fight
# entirely, and it also leaves the box's sibling vhosts untouched, since they
# carry an explicit `server_name` and so never reach this code at all.

[ -n "${_NWP_SERVER_HOST_GUARD_SOURCED:-}" ] && return 0
_NWP_SERVER_HOST_GUARD_SOURCED=1

HOST_GUARD_MARKER="# NWP-HOST-GUARD v1"

# Hosts that are ALWAYS admitted. nginx-status, `gitlab-ctl` health probes and
# anything looping back over 127.0.0.1 must not be 444'd by a guard that exists
# to stop STRANGERS. Locking yourself out of your own box is not security.
HOST_GUARD_ALWAYS=("localhost" "127.0.0.1")

# The Host header used to prove the guard bites. `.invalid` is reserved by
# RFC 2606 and can never resolve, so this probe cannot collide with a real name.
HOST_GUARD_PROBE_HOST="nwp-host-guard-probe.invalid"

################################################################################
# SECTION 1 — validation
################################################################################

# _host_guard_valid_name <name>
# A hostname or bare IP. Deliberately strict: this string is spliced into an
# nginx config, so anything that could carry a quote, a newline, a semicolon or
# a brace is refused outright rather than escaped and hoped for.
_host_guard_valid_name() {
    local n="$1"
    [ -n "$n" ] || return 1
    [ "${#n}" -le 253 ] || return 1
    [[ "$n" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)*$ ]]
}

# _host_guard_escape <name>  -> the name with regex metacharacters escaped.
# Only `.` can occur in a name that passed validation, but escaping is done by
# rule rather than by "the only one that can appear", so widening the validator
# later cannot silently widen the regex.
_host_guard_escape() {
    printf '%s' "$1" | sed -e 's/[.[\*^$()+?{}|\\]/\\&/g'
}

################################################################################
# SECTION 2 — rendering the guard
################################################################################

# host_guard_regex <host>...  -> the anchored alternation nginx will test $host against.
host_guard_regex() {
    local -a names=("$@")
    local n alt=""
    for n in "${names[@]}" "${HOST_GUARD_ALWAYS[@]}"; do
        alt+="${alt:+|}$(_host_guard_escape "$n")"
    done
    # Anchored at BOTH ends so neither `evil-forge.example.com` (prefix) nor
    # `forge.example.com.attacker.test` (suffix) can smuggle itself through.
    # The optional `:port` is tolerated because a client may send host:port and
    # nginx's $host does not always strip it.
    printf '^(%s)(:[0-9]+)?$' "$alt"
}

# host_guard_render <host>...
# Emits the snippet for nginx['custom_gitlab_server_config'].
host_guard_render() {
    if [ "$#" -eq 0 ]; then
        echo "REFUSING to render a host guard with an empty allowlist — that would" >&2
        echo "return 444 for every request and take the box off the internet." >&2
        return 2
    fi
    local n
    for n in "$@"; do
        if ! _host_guard_valid_name "$n"; then
            echo "REFUSING: '${n}' is not a plain hostname or IP. This string is spliced" >&2
            echo "into an nginx config; it is refused, not escaped." >&2
            return 2
        fi
    done

    local re; re="$(host_guard_regex "$@")"
    cat <<EOF
${HOST_GUARD_MARKER} — nwp/ops#381. Managed by \`pl server host-guard\`; do not hand-edit.
# Unmatched Host headers get 444 (close, no response) instead of the whole
# application. 444 rather than 404 because a 404 still ships a body, and the
# incident that prompted this was a BANDWIDTH event: 13.1 GB in one morning.
if (\$host !~* "${re}") {
    return 444;
}
EOF
}

# host_guard_matches <snippet> <host>
# 0 = admitted, 1 = would be 444'd, 2 = no guard regex found in the snippet.
# Evaluates the SAME regex nginx would, so the tests assert on the artefact that
# actually gets installed rather than on a restatement of it.
host_guard_matches() {
    local snippet="$1" host="$2" re
    # No `… | head -1`. Under `set -o pipefail` head closes the pipe, the writer
    # takes SIGPIPE (141), and THAT becomes the pipeline's status — so the branch
    # below would be decided by timing rather than by content (ops#351). awk does
    # its own first-match-then-stop and exits 0 either way.
    re="$(awk 'match($0, /!~\* "[^"]*"/) { print substr($0, RSTART + 5, RLENGTH - 6); exit }' <<<"$snippet")"
    [ -n "$re" ] || return 2
    local rc=1
    shopt -s nocasematch
    [[ "$host" =~ $re ]] && rc=0
    shopt -u nocasematch
    return $rc
}

# host_guard_gitlab_rb_line <snippet-path>  -> the gitlab.rb assignment.
host_guard_gitlab_rb_line() {
    printf "nginx['custom_gitlab_server_config'] = File.read('%s')\n" "$1"
}

################################################################################
# SECTION 3 — the remote probe
################################################################################

# host_guard_probe_script <real-host> [bogus-host]
# Asks the box, from the box, what it serves for a Host it has never heard of.
# Runs against 127.0.0.1 so it needs no DNS and never leaves the machine.
#
# It also reports the facts the APPLY path needs, so a repair never has to guess:
# which hostname GitLab believes it is, and whether a guard is already seated.
host_guard_probe_script() {
    local real="$1" bogus="${2:-$HOST_GUARD_PROBE_HOST}"
    cat <<EOF
set -u
printf 'NWPHOSTGUARD v1\n'
printf 'real_host=%s\n' '${real}'
printf 'bogus_host=%s\n' '${bogus}'
c=\$(curl -s -o /dev/null -w '%{http_code}' -k --max-time 15 \\
      -H 'Host: ${real}' https://127.0.0.1/ 2>/dev/null || printf '000')
printf 'real_code=%s\n' "\$c"
c=\$(curl -s -o /dev/null -w '%{http_code}' -k --max-time 15 \\
      -H 'Host: ${bogus}' https://127.0.0.1/ 2>/dev/null || printf '000')
printf 'bogus_code=%s\n' "\$c"

# Which nginx is this? MEASURED, never inferred from the host's name.
if [ -d /opt/gitlab ]; then printf 'gitlab_embedded=yes\n'; else printf 'gitlab_embedded=no\n'; fi

# What hostname does GitLab believe it is? This is the allowlist's whole content:
# the guard sits INSIDE GitLab's server block, which is only reached by requests
# that already failed to match every other vhost's server_name.
if sudo -n test -r /etc/gitlab/gitlab.rb 2>/dev/null; then
  printf 'gitlab_rb_readable=yes\n'
  u=\$(sudo -n sed -n "s/^ *external_url *['\"]\\([^'\"]*\\)['\"].*/\\1/p" /etc/gitlab/gitlab.rb 2>/dev/null | tail -1)
  printf 'gitlab_external_url=%s\n' "\$u"
  if sudo -n grep -q 'NWP-HOST-GUARD' /etc/gitlab/gitlab.rb 2>/dev/null; then
    printf 'guard_declared=yes\n'
  else
    printf 'guard_declared=no\n'
  fi
else
  printf 'gitlab_rb_readable=no\n'
fi
EOF
}

# host_guard_fact <facts-file> <key>  -> the first value for <key>, or empty.
#
# Pipe-free ON PURPOSE. `sed -n 's/^k=//p' f | head -1` looks equivalent and is
# not: head closes the pipe after one line, sed dies of SIGPIPE, and under
# `set -o pipefail` the caller reads 141 as the verdict (ops#351). awk stops at
# the first hit by itself and exits 0 whether or not the key was found — absence
# is reported as an empty value, which is a fact, not a failure.
host_guard_fact() {
    awk -v k="$2" 'index($0, k "=") == 1 { print substr($0, length(k) + 2); exit }' "$1" 2>/dev/null
}

# host_guard_host_of_url <url>  -> the hostname, stripped of scheme/port/path.
host_guard_host_of_url() {
    local u="${1#*://}"
    u="${u%%/*}"
    u="${u%%:*}"
    printf '%s' "$u"
}

################################################################################
# SECTION 4 — the verdict
################################################################################

# host_guard_verdict <facts-file>
#   0 = GUARDED · 1 = PROMISCUOUS · 3 = CANNOT VERIFY
#
# FAIL-CLOSED, in the direction that matters. The tempting default is "no answer
# means fine"; here that would report a wide-open box as guarded. Every path that
# did not actually MEASURE both probes exits 3, and exit 3 is never graded green.
host_guard_verdict() {
    local f="${1:-}"
    if [ -z "$f" ] || [ ! -r "$f" ]; then
        echo "CANNOT VERIFY: no host-guard probe capture to read — this is NOT 'guarded'"
        return 3
    fi
    if ! grep -q '^NWPHOSTGUARD v1$' "$f" 2>/dev/null; then
        echo "CANNOT VERIFY: the probe capture has no version banner — refusing to grade"
        return 3
    fi

    local real_host real_code bogus_host bogus_code
    real_host="$(host_guard_fact "$f" real_host)"
    real_code="$(host_guard_fact "$f" real_code)"
    bogus_host="$(host_guard_fact "$f" bogus_host)"
    bogus_code="$(host_guard_fact "$f" bogus_code)"

    if [ -z "$real_code" ] || [ -z "$bogus_code" ]; then
        echo "CANNOT VERIFY: a probe did not report a status code — refusing to grade"
        return 3
    fi

    # The control. If the box did not answer for its OWN name, nothing can be
    # concluded about what it does for a stranger's: a closed connection then
    # means "down", not "guarded". This is the branch that stops a dead box from
    # being scored as a hardened one.
    if [ "$real_code" = "000" ]; then
        echo "CANNOT VERIFY: the box did not answer for its own name (${real_host})."
        echo "               A closed connection here means DOWN, not guarded."
        return 3
    fi

    if [ "$bogus_code" = "000" ] || [ "$bogus_code" = "444" ]; then
        echo "GUARDED — an unknown Host (${bogus_host}) is refused, while ${real_host} is served (${real_code})."
        return 0
    fi

    echo "PROMISCUOUS — this box served HTTP ${bogus_code} for '${bogus_host}',"
    echo "              a Host header it has no reason to recognise."
    echo "              Any hostname pointed at this IP gets the application."
    echo "              This is the ops#381 defect. Fix: pl server host-guard <server> --apply"
    return 1
}
