<?php

/**
 * @file
 * Install, update and uninstall functions for the shariff module.
 */

/**
 * Implements hook_requirements().
 */
function shariff_requirements($phase) {
  $requirements = [];

  // Check if library is available.
  $library_shariff = \Drupal::service('library.libraries_directory_file_finder')->find('shariff');

  if ($library_shariff === FALSE) {
    // The shariff library hasn't been found.
    $requirements['shariff_lib'] = [
      'title' => t('Shariff Library'),
      'description' => t('Please download at least v1.4.6 of the <a href=":url">shariff library</a> and place it in one of your libraries folders. So that for example the js file is available under DRUPAL_ROOT/libraries/shariff/shariff.min.js.', [':url' => 'https://github.com/heiseonline/shariff/releases/latest']),
      'severity' => REQUIREMENT_ERROR,
    ];
  }
  else {
    $requirements['shariff_lib'] = [
      'title' => t('Shariff Library'),
      'severity' => REQUIREMENT_OK,
      'value' => t('Available'),
    ];
  }

  return $requirements;
}

/**
 * Remove googleplus service.
 */
function shariff_update_8001() {
  \Drupal::configFactory()->getEditable('shariff.settings')
    ->clear('shariff_services.googleplus')
    ->save(TRUE);
}
