"""Configuration loader for Mass Times scraper.

Reads mass-times.conf (generated by deploy-mass-times.sh from nwp.yml)
and provides typed access to configuration values.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class MassTimesConfig:
    """Configuration for the Mass Times scraper."""

    # Geographic scope
    centre_lat: float = -37.8131  # Ringwood, Melbourne
    centre_lng: float = 145.2285
    radius_km: float = 20.0

    # LLM settings (Tier 3 fallback only)
    fallback_model: str = "claude-sonnet-4-5"
    max_monthly_llm_usd: float = 5.0
    tier3_daily_limit: int = 10

    # API keys
    claude_api_key: str = ""
    google_places_api_key: str = ""
    drupal_api_password: str = ""

    # Email
    alert_on_failure: bool = True
    weekly_summary: bool = True
    email_recipients: str = ""
    email_from: str = ""

    # Drupal sync
    drupal_site: str = "mt"
    drupal_api_user: str = "mass_times_bot"
    drupal_base_url: str = ""
    sync_after_extraction: bool = True

    # Paths
    base_dir: Path = field(default_factory=lambda: Path(__file__).parent.parent)
    templates_dir: Path = field(default_factory=lambda: Path(__file__).parent.parent / "templates")
    data_dir: Path = field(default_factory=lambda: Path(__file__).parent.parent / "data")

    # Shadow mode: flag all data as provisional
    shadow_mode: bool = True

    # Timezone
    timezone: str = "Australia/Sydney"


def load_config(conf_path: str | None = None) -> MassTimesConfig:
    """Load configuration from mass-times.conf file.

    The conf file is a bash-style key=value file generated by
    deploy-mass-times.sh from nwp.yml.
    """
    config = MassTimesConfig()

    if conf_path is None:
        conf_path = str(config.base_dir / "mass-times.conf")

    if not os.path.exists(conf_path):
        return config

    env = {}
    with open(conf_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                # Strip quotes
                value = value.strip().strip('"').strip("'")
                env[key.strip()] = value

    # Map conf keys to config fields
    mapping = {
        "MT_CENTRE_LAT": ("centre_lat", float),
        "MT_CENTRE_LNG": ("centre_lng", float),
        "MT_RADIUS_KM": ("radius_km", float),
        "MT_FALLBACK_MODEL": ("fallback_model", str),
        "MT_MAX_MONTHLY_LLM_USD": ("max_monthly_llm_usd", float),
        "MT_TIER3_DAILY_LIMIT": ("tier3_daily_limit", int),
        "MT_CLAUDE_API_KEY": ("claude_api_key", str),
        "MT_GOOGLE_PLACES_API_KEY": ("google_places_api_key", str),
        "MT_DRUPAL_API_PASSWORD": ("drupal_api_password", str),
        "MT_ALERT_ON_FAILURE": ("alert_on_failure", lambda v: v.lower() in ("true", "1", "yes")),
        "MT_WEEKLY_SUMMARY": ("weekly_summary", lambda v: v.lower() in ("true", "1", "yes")),
        "MT_EMAIL_RECIPIENTS": ("email_recipients", str),
        "MT_EMAIL_FROM": ("email_from", str),
        "MT_DRUPAL_SITE": ("drupal_site", str),
        "MT_DRUPAL_API_USER": ("drupal_api_user", str),
        "MT_DRUPAL_BASE_URL": ("drupal_base_url", str),
        "MT_SYNC_AFTER_EXTRACTION": ("sync_after_extraction", lambda v: v.lower() in ("true", "1", "yes")),
        "MT_SHADOW_MODE": ("shadow_mode", lambda v: v.lower() in ("true", "1", "yes")),
        "MT_TIMEZONE": ("timezone", str),
    }

    for conf_key, (attr, converter) in mapping.items():
        if conf_key in env:
            try:
                setattr(config, attr, converter(env[conf_key]))
            except (ValueError, TypeError):
                pass  # Keep default if conversion fails

    return config
