<?php

/**
 * @file
 * Contains ginvite.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\ginvite\Event\UserLoginWithInvitationEvent;
use Drupal\ginvite\Event\UserRegisteredFromInvitationEvent;
use Drupal\ginvite\Plugin\GroupContentEnabler\GroupInvitation;
use Drupal\group\Access\GroupAccessResult;
use Drupal\group\Entity\GroupContentInterface;
use Drupal\group\Entity\GroupInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function ginvite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ginvite':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for group_content_form.
 */
function ginvite_form_group_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\ContentEntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
  $group_content = $form_object->getEntity();
  $content_plugin = $group_content->getContentPlugin();
  if ($content_plugin->getPluginId() === 'group_invitation') {
    $form += [
      // Reference to Anonymous user by default.
      'entity_id' => [
        '#type' => 'value',
        '#value' => 0,
      ],
    ];

    // Is there a group associated with this form instance?
    $group = $group_content->getGroup();
    // Forbid users without the permission to assign roles to users they are
    // inviting.
    if ($group instanceof GroupInterface && !GroupAccessResult::allowedIfHasGroupPermission($group, \Drupal::currentUser(), 'administer members')->isAllowed()) {
      $form['group_roles']['#access'] = FALSE;
    }
  }
}

/**
 * Sends email when invitation created for not registered user.
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function ginvite_group_content_insert(GroupContentInterface $group_content) {
  $type = $group_content->getContentPlugin()->getPluginId();
  $messenger = \Drupal::messenger();

  if ($type == 'group_invitation') {
    $mail = $group_content->get('invitee_mail')->getString();

    // If invited user has no mail, don't try to send one.
    if (empty($mail)) {
      // "Invitee mail" can be hidden.
      // More info: https://www.drupal.org/project/ginvite/issues/3206103
      // Try to get user from "Invitee" field.
      $uid = $group_content->get('entity_id')->getString();
      // We want to be sure user exists.
      if (!empty($uid) && ($invitee = User::load($uid))) {
        $messenger->addMessage(t('Invite sent to %username', ['%username' => $invitee->getDisplayName()]));

        $group_content->set('invitation_status', GroupInvitation::INVITATION_PENDING);
        $group_content->save();
      }
    }
    else {
      $mail_manager = \Drupal::service('plugin.manager.mail');
      $from = $group_content->getEntity();
      $group = $group_content->getGroup();
      $params = [
        'user' => $from,
        'group' => $group,
        'group_content' => $group_content,
        'existing_user' => FALSE,
      ];
      $langcode = $from->getPreferredLangcode();

      // Load plugin configuration.
      $group_plugin_collection = \Drupal::service('plugin.manager.group_content_enabler')
        ->getInstalled($group->getGroupType());
      $group_invite_config = $group_plugin_collection->getConfiguration()['group_invitation'];

      if ($invitee = user_load_by_mail($mail)) {
        $group_content->set('entity_id', $invitee);

        // Check if we should send an email to existing user.
        if ($group_invite_config['send_email_existing_users']) {
          $params['existing_user'] = TRUE;
          $mail_manager->mail('ginvite', 'invite', $mail, $langcode, $params, NULL, TRUE);
          $messenger->addMessage(t('Invite sent to %invitee', ['%invitee' => $invitee->getDisplayName()]));
        }
        else {
          $messenger->addMessage(t('Invitation has been created.'));
        }
      }
      else {
        $mail_manager->mail('ginvite', 'invite', $mail, $langcode, $params, NULL, TRUE);
        $messenger->addMessage(t('Invite sent to %mail', ['%mail' => $mail]));
      }

      $group_content->set('invitation_status', GroupInvitation::INVITATION_PENDING);
      $group_content->save();
    }
  }
  // If new membership is created, check related invitation exists.
  elseif ($type == 'group_membership') {
    $properties = [
      'entity_id' => $group_content->getEntity()->id(),
      'gid' => $group_content->getGroup()->id(),
      'invitation_status' => GroupInvitation::INVITATION_PENDING,
    ];

    $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
    if (!empty($invitations)) {

      foreach ($invitations as $invitation) {
        // Remove group content if setting is enabled.
        if ($invitation->getGroupContent()->getContentPlugin()->getConfiguration()['remove_invitation'] == 1) {
          $invitation->getGroupContent()->delete();
        }
        else {
          // Mark invitation as accepted.
          $invitation->getGroupContent()->set('invitation_status', GroupInvitation::INVITATION_ACCEPTED)->save();
        }
      }

      $messenger->addMessage(t('You have accepted the invitation.'));
    }
  }
}

/**
 * Send cancellation email when the invitation is removed.
 *
 * Implements hook_ENTITY_TYPE_delete().
 */
function ginvite_group_content_delete(GroupContentInterface $group_content) {
  if ($group_content->getContentPlugin()->getPluginId() == 'group_invitation') {
    $group = $group_content->getGroup();
    // Load plugin configuration.
    $group_invite_config = $group_content->getContentPlugin()->getConfiguration();

    if ($group_invite_config['send_cancel_email'] && $group_content->get('invitation_status')->value == GroupInvitation::INVITATION_PENDING) {
      $from = $group_content->getEntity();

      if ($from instanceof UserInterface) {
        $mail = $group_content->get('invitee_mail')->getString();
        $params = [
          'user' => $from,
          'group' => $group,
          'group_content' => $group_content,
        ];
        $langcode = $from->getPreferredLangcode();
        \Drupal::service('plugin.manager.mail')->mail('ginvite', 'cancel', $mail, $langcode, $params, NULL, TRUE);
      }
    }
  }

  if ($group_content->getContentPlugin()->getPluginId() == 'group_membership') {
    // The user was removed and there is no entity.
    if (empty($group_content->getEntity())) {
      return;
    }

    $properties = [
      'entity_id' => $group_content->getEntity()->id(),
      'gid' => $group_content->getGroup()->id(),
    ];

    // Remove invitations, when we remove the user.
    $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
    foreach ($invitations as $invitation) {
      $invitation->getGroupContent()->delete();
    }
  }
}

/**
 * Implements hook_mail().
 *
 * This mail is sent when people who do not have an account on the website yet
 * are invited into a group. It is sent in the language the inviter was using
 * the website in.
 *
 * @see ginvite_group_content_insert()
 */
function ginvite_mail($key, &$message, $params) {
  if ($key == 'invite' || $key == 'cancel') {
    $token_service = \Drupal::token();
    $language_manager = \Drupal::languageManager();

    // Get email from GroupInvitation.
    $group = $params['group'];
    $langcode = $message['langcode'];

    $language = $language_manager->getLanguage($langcode);
    $original_language = $language_manager->getConfigOverrideLanguage();
    $language_manager->setConfigOverrideLanguage($language);

    // Load plugin configuration.
    $group_plugin_collection = \Drupal::service('plugin.manager.group_content_enabler')->getInstalled($group->getGroupType());
    $group_invite_config = $group_plugin_collection->getConfiguration()['group_invitation'];

    $language_manager->setConfigOverrideLanguage($original_language);
    $subject = '';
    $body = '';
    if ($key == 'cancel') {
      $subject = $group_invite_config['cancel_user_invitation_subject'];
      $body = $group_invite_config['cancel_user_invitation_body'];
    }

    if ($key == 'invite') {
      $subject = (!$params['existing_user']) ? $group_invite_config['invitation_subject'] : $group_invite_config['existing_user_invitation_subject'];
      $body = (!$params['existing_user']) ? $group_invite_config['invitation_body'] : $group_invite_config['existing_user_invitation_body'];

      unset($params['existing_user']);
    }

    $body = $token_service->replace($body, $params);
    $subject = $token_service->replace($subject, $params);

    $message['subject'] = $subject;
    $message['body'][] = $body;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ginvite_user_insert(UserInterface $user) {
  _ginvite_handle_new_user_registration_or_update($user);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function ginvite_user_update(UserInterface $user) {
  _ginvite_handle_new_user_registration_or_update($user);
}

/**
 * Handles when a new user registers or an existing gets updated.
 *
 * Sets entity reference property on pending invitations of a previously
 * non-existing user by email.
 *
 * @param \Drupal\user\UserInterface $user
 *   A user.
 */
function _ginvite_handle_new_user_registration_or_update(UserInterface $user) {
  // If a user is created without e-mail (because the field is optional or
  // because they are created through SSO) then we can not use the mail to check
  // for pending invites, so we exit early.
  if ($user->get('mail')->isEmpty()) {
    return;
  }

  $properties = [
    'invitee_mail' => $user->getEmail(),
    'invitation_status' => GroupInvitation::INVITATION_PENDING,
    // For security reasons we only allow to get the ownership of invitations
    // that previously belonged to a non-existing user, once the owner is set
    // they cannot be reassigned (for example, by simply changing email
    // addresses).
    'entity_id' => 0,
  ];

  /** @var \Drupal\ginvite\GroupInvitation[] $invitations */
  $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $event_dispatcher */
  $event_dispatcher = \Drupal::service('event_dispatcher');
  foreach ($invitations as $invitation) {
    $group_content = $invitation->getGroupContent();
    $group_content->set('entity_id', $user->id());
    $group_content->save();
    // Dispatch an event when the user is registered from an invitation.
    // It is not that simple identifying that due to some SSO implementation
    // that usually creates a stub user first and only starts filling in
    // fields on the object, so $user->isNew() is not a viable option here.
    // @todo Should we trigger new event when an existing users change their
    //   email address to one that belongs to a pending invitation?
    if ($user->getLastLoginTime() === 0) {
      $event = new UserRegisteredFromInvitationEvent($invitation);
      $event_dispatcher->dispatch($event, UserRegisteredFromInvitationEvent::EVENT_NAME);
    }
  }
}

/**
 * Add Constraint to prevent duplicated invitations.
 *
 * Implements hook_entity_type_alter().
 */
function ginvite_entity_type_alter(array &$entity_types) {
  $group_content = $entity_types['group_content'];
  $group_content->addConstraint('PreventDuplicated', []);
}

/**
 * Add token to register url.
 *
 * Implements hook_token_info().
 */
function ginvite_token_info() {
  $tokens = [];
  $tokens['register_link'] = [
    'name' => t('Register Link'),
    'description' => t('Url to register page with prefilled email address.'),
  ];
  $tokens['my_invitations_link'] = [
    'name' => t('My Invitations Link'),
    'description' => t('Url to user list of invitations.'),
  ];

  return [
    'tokens' => ['group_content' => $tokens],
  ];
}

/**
 * Implements hook_tokens().
 */
function ginvite_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'group_content' && !empty($data[$type])) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group_content = $data['group_content'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'register_link':
          $mail = $group_content->get('invitee_mail')->getString();
          $search = ['+', '/', '='];
          $replace = ['-', '_', ''];
          $mail_encoded = str_replace($search, $replace, base64_encode($mail));
          $params = ['invitee_mail' => $mail_encoded];
          $options = ['absolute' => TRUE];
          $register_link = Url::fromRoute('user.register', $params, $options)->toString();
          $replacements[$original] = $register_link;
          break;

        case 'my_invitations_link':
          $user = user_load_by_mail($group_content->get('invitee_mail')->getString());
          $my_invitations_link = Url::fromRoute('view.my_invitations.page_1', ['user' => $user->id()], ['absolute' => TRUE])->toString();
          $replacements[$original] = $my_invitations_link;
      }
    }
  }
  return $replacements;
}

/**
 * Prefill email address when user comes from ginvite registrarion url.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function ginvite_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $invitee_mail = \Drupal::request()->query->get('invitee_mail');
  if (isset($invitee_mail)) {
    $search = ['-', '_'];
    $replace = ['+', '/'];
    $invitee_mail = base64_decode(str_replace($search, $replace, $invitee_mail));
    if (\Drupal::service('email.validator')->isValid($invitee_mail)) {
      $form['account']['mail']['#default_value'] = $invitee_mail;
      $form['account']['mail']['#disabled'] = TRUE;
    }
    $form['#cache']['max-age'] = 0;
  }

}

/**
 * Remove invites that are expired based on group type configuration.
 *
 * Implements hook_cron().
 */
function ginvite_cron() {
  $last_check = \Drupal::state()->get('ginvite.last_expire_removal', 0);
  $interval = 60 * 60 * 24;
  $request_time = \Drupal::time()->getRequestTime();

  // Only run this once a day.
  if (($request_time - $last_check) < $interval) {
    return;
  }

  $entity_type_manager = \Drupal::entityTypeManager();
  $content_enabler_manager = \Drupal::service('plugin.manager.group_content_enabler');
  $group_type_storage = $entity_type_manager->getStorage('group_type');
  $group_content_storage = $entity_type_manager->getStorage('group_content');
  /** @var \Drupal\group\Entity\GroupTypeInterface $group_type */
  foreach ($group_type_storage->loadMultiple() as $group_type) {
    // Foreach group type get the configuration for the invites expired time.
    $group_plugin_collection = $content_enabler_manager->getInstalled($group_type);
    $days = $group_plugin_collection->getConfiguration()['group_invitation']['invitation_expire'] ?? NULL;
    $keep_invitations = (bool) ($group_plugin_collection->getConfiguration()['group_invitation']['invitation_expire_keep'] ?? FALSE);

    // Nothing configured? Skip.
    if (!$days) {
      continue;
    }

    // Query for all the invites that are expired for this group type.
    $config_id = $group_type->getContentPlugin('group_invitation')->getContentTypeConfigId();
    $expired_invites = $group_content_storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('type', $config_id)
      ->condition('invitation_status', GroupInvitation::INVITATION_PENDING)
      ->condition('created', $request_time - ($days * $interval), '<')
      ->execute();

    // No expired invites? Skip.
    if (empty($expired_invites)) {
      continue;
    }

    $group_invitations = $group_content_storage->loadMultiple($expired_invites);
    if ($keep_invitations) {
      foreach ($group_invitations as $invitation) {
        // Mark invitation as expired.
        $invitation->set('invitation_status', GroupInvitation::INVITATION_EXPIRED)->save();
      }
    }
    else {
      // Permanently remove all expired invites.
      $group_content_storage->delete($group_invitations);
    }

  }

  // Set the time that we removed the expired invites so we don't do it too
  // often.
  \Drupal::state()->set('ginvite.last_expire_removal', $request_time);
}

/**
 * Implements hook_user_login().
 */
function ginvite_user_login(UserInterface $user) {
  // If a user is created without e-mail (because the field is optional or
  // because they are created through SSO) then we can not use the mail to check
  // for pending invites, so we exit early.
  if ($user->get('mail')->isEmpty()) {
    return;
  }

  $properties = [
    'invitee_mail' => $user->getEmail(),
    'invitation_status' => GroupInvitation::INVITATION_PENDING,
    'entity_id' => $user->id(),
  ];

  /** @var \Drupal\ginvite\GroupInvitation[] $invitations */
  $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $event_dispatcher */
  $event_dispatcher = \Drupal::service('event_dispatcher');
  foreach ($invitations as $invitation) {
    $event = new UserLoginWithInvitationEvent($invitation);
    $event_dispatcher->dispatch($event, UserLoginWithInvitationEvent::EVENT_NAME);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function ginvite_group_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'view' || $operation == 'view label') {
    $properties = [
      'entity_id' => $account->id(),
      'gid' => $entity->id(),
      'invitation_status' => GroupInvitation::INVITATION_PENDING,
    ];

    $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
    if (!empty($invitations)) {
      return AccessResult::allowed();
    }
  }

  return AccessResult::neutral();
}
