#!/bin/bash
################################################################################
# email-reroute.sh - Email rerouting configuration for development safety
#
# This library provides functions to configure email rerouting in Drupal/PHP
# applications to prevent accidental emails to real users during development.
#
# Usage:
#   source /path/to/email-reroute.sh
#   email_reroute_drupal_config "/path/to/site" "dev@example.com"
#
# Features:
#   - Redirects all outgoing emails to a test address
#   - Supports whitelist patterns (e.g., *@nwpcode.org)
#   - Per-site configuration via cnwp.yml
#   - Drupal Reroute Email module integration
################################################################################

# Configuration
REROUTE_DEFAULT_EMAIL="${REROUTE_DEFAULT_EMAIL:-dev@nwpcode.org}"
REROUTE_WHITELIST="${REROUTE_WHITELIST:-*@nwpcode.org}"

################################################################################
# Generate Drupal settings.php reroute configuration
#
# Arguments:
#   $1 - Reroute email address
#   $2 - Whitelist patterns (comma-separated)
#   $3 - Enable flag (1 or 0)
################################################################################
generate_drupal_reroute_config() {
    local reroute_to="${1:-$REROUTE_DEFAULT_EMAIL}"
    local whitelist="${2:-$REROUTE_WHITELIST}"
    local enabled="${3:-1}"

    cat << EOF
/**
 * Email rerouting configuration for development safety.
 * Generated by NWP email-reroute.sh
 *
 * All outgoing emails will be redirected to: $reroute_to
 * Whitelist patterns: $whitelist
 */
\$config['reroute_email.settings']['enable'] = $enabled;
\$config['reroute_email.settings']['address'] = '$reroute_to';
\$config['reroute_email.settings']['whitelist'] = '$whitelist';
\$config['reroute_email.settings']['description'] = TRUE;
\$config['reroute_email.settings']['message'] = TRUE;
\$config['reroute_email.settings']['mailkeys'] = '';
EOF
}

################################################################################
# Generate PHP mail configuration for non-Drupal apps
#
# Arguments:
#   $1 - Reroute email address
################################################################################
generate_php_mail_override() {
    local reroute_to="${1:-$REROUTE_DEFAULT_EMAIL}"

    cat << EOF
<?php
/**
 * Email rerouting for development.
 * Include this file in your application bootstrap.
 * Generated by NWP email-reroute.sh
 */

// Override mail function to reroute all emails
function dev_mail(\$to, \$subject, \$message, \$headers = '', \$params = '') {
    \$reroute_to = '$reroute_to';

    // Add original recipient to subject
    \$subject = "[REROUTED from: \$to] " . \$subject;

    // Add reroute header
    if (is_string(\$headers)) {
        \$headers .= "\r\nX-Original-To: \$to";
    }

    // Send to reroute address
    return mail(\$reroute_to, \$subject, \$message, \$headers, \$params);
}

// Override the mail function (requires runkit or uopz extension)
// Or use this in your mail wrapper
EOF
}

################################################################################
# Generate Postfix transport map for email rerouting
#
# Arguments:
#   $1 - Reroute email address
#   $2 - Whitelist patterns (comma-separated domain patterns)
################################################################################
generate_postfix_reroute() {
    local reroute_to="${1:-$REROUTE_DEFAULT_EMAIL}"
    local whitelist="${2:-nwpcode.org}"

    cat << EOF
# Postfix email rerouting configuration
# Generated by NWP email-reroute.sh
#
# Add to /etc/postfix/main.cf:
#   recipient_canonical_maps = regexp:/etc/postfix/recipient_canonical_reroute
#
# Then run: postmap /etc/postfix/recipient_canonical_reroute && postfix reload

# Whitelist - these addresses pass through unchanged
EOF

    # Generate whitelist rules
    IFS=',' read -ra PATTERNS <<< "$whitelist"
    for pattern in "${PATTERNS[@]}"; do
        pattern=$(echo "$pattern" | xargs)  # Trim whitespace
        echo "/.*@${pattern}\$/    \$0"
    done

    cat << EOF

# Reroute everything else
/^(.*)@(.*)$/   ${reroute_to}
EOF
}

################################################################################
# Apply reroute configuration to a Drupal site
#
# Arguments:
#   $1 - Site directory path
#   $2 - Reroute email address
#   $3 - Whitelist patterns
################################################################################
apply_drupal_reroute() {
    local site_dir="$1"
    local reroute_to="${2:-$REROUTE_DEFAULT_EMAIL}"
    local whitelist="${3:-$REROUTE_WHITELIST}"

    local settings_file="${site_dir}/html/sites/default/settings.local.php"

    # Check if site exists
    if [ ! -d "$site_dir" ]; then
        echo "Error: Site directory not found: $site_dir" >&2
        return 1
    fi

    # Check for reroute_email module
    if [ -d "${site_dir}/html/modules/contrib/reroute_email" ]; then
        echo "Found reroute_email module, generating config..."

        # Generate and append config
        echo "" >> "$settings_file"
        generate_drupal_reroute_config "$reroute_to" "$whitelist" >> "$settings_file"

        echo "Reroute configuration added to: $settings_file"
        echo "All emails will be sent to: $reroute_to"
    else
        echo "Warning: reroute_email module not found" >&2
        echo "Install with: ddev composer require drupal/reroute_email" >&2
        echo "Then enable: ddev drush en reroute_email" >&2
        return 1
    fi
}

################################################################################
# Check reroute status for a site
#
# Arguments:
#   $1 - Site directory path
################################################################################
check_reroute_status() {
    local site_dir="$1"
    local settings_file="${site_dir}/html/sites/default/settings.local.php"

    echo "Email Reroute Status for: $site_dir"
    echo "=================================="

    # Check for reroute_email module
    if [ -d "${site_dir}/html/modules/contrib/reroute_email" ]; then
        echo "Reroute Email Module: INSTALLED"
    else
        echo "Reroute Email Module: NOT INSTALLED"
    fi

    # Check settings.local.php for config
    if [ -f "$settings_file" ]; then
        if grep -q "reroute_email" "$settings_file"; then
            echo "Configuration: FOUND in settings.local.php"
            local reroute_to=$(grep "reroute_email.settings.*address" "$settings_file" | grep -oP "'[^']+'" | tail -1 | tr -d "'")
            echo "Reroute To: ${reroute_to:-unknown}"
        else
            echo "Configuration: NOT FOUND"
        fi
    else
        echo "Settings File: NOT FOUND ($settings_file)"
    fi
}

################################################################################
# Generate DDEV settings for email rerouting via Mailpit
################################################################################
generate_ddev_mailpit_settings() {
    cat << 'EOF'
<?php
/**
 * DDEV Mailpit email configuration.
 * All emails sent via Drupal's mail system will go to Mailpit.
 *
 * Add this to settings.local.php or settings.ddev.php
 */

// Configure SMTP to use Mailpit
$config['symfony_mailer.mailer_transport.smtp']['configuration'] = [
  'host' => 'mailpit',
  'port' => 1025,
];

// Or if using Drupal's native mail (requires SMTP module or similar)
$config['smtp.settings']['smtp_host'] = 'mailpit';
$config['smtp.settings']['smtp_port'] = '1025';
$config['smtp.settings']['smtp_protocol'] = 'standard';

// Alternative: Force all mail through PHP's sendmail via Mailpit
// ini_set('sendmail_path', '/usr/sbin/sendmail -t -i -S mailpit:1025');
EOF
}

################################################################################
# Parse site email config from cnwp.yml
#
# Arguments:
#   $1 - Site name
#   $2 - cnwp.yml path
################################################################################
get_site_email_config() {
    local site_name="$1"
    local config_file="${2:-cnwp.yml}"

    if [ ! -f "$config_file" ]; then
        echo ""
        return 1
    fi

    # Parse email configuration for site
    # Expected structure:
    # sites:
    #   sitename:
    #     email:
    #       reroute_to: dev@example.com
    #       whitelist: "*@nwpcode.org"
    #       enabled: true

    python3 << EOF 2>/dev/null || echo ""
import yaml
try:
    with open('$config_file', 'r') as f:
        config = yaml.safe_load(f)
    sites = config.get('sites', {})
    site = sites.get('$site_name', {})
    email = site.get('email', {})
    if email:
        reroute = email.get('reroute_to', '')
        whitelist = email.get('whitelist', '')
        enabled = email.get('enabled', True)
        print(f"{reroute}|{whitelist}|{enabled}")
except Exception:
    pass
EOF
}

################################################################################
# Main - show help when run directly
################################################################################
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cat << 'EOF'
Email Reroute Library - Development Safety for Email

This library provides functions to prevent accidental emails to real users
during development and testing.

Usage:
  source email-reroute.sh

Functions:
  generate_drupal_reroute_config <email> [whitelist] [enabled]
      Generate Drupal settings.php configuration

  generate_php_mail_override <email>
      Generate PHP mail override code

  generate_postfix_reroute <email> [whitelist]
      Generate Postfix recipient canonical map

  apply_drupal_reroute <site_dir> [email] [whitelist]
      Apply reroute configuration to a Drupal site

  check_reroute_status <site_dir>
      Check current reroute configuration

  generate_ddev_mailpit_settings
      Generate DDEV Mailpit integration settings

  get_site_email_config <site_name> [config_file]
      Parse email config from cnwp.yml

Examples:
  # Generate Drupal config
  generate_drupal_reroute_config "dev@test.com" "*@nwpcode.org"

  # Apply to site
  apply_drupal_reroute "/home/user/nwp/mysite" "dev@test.com"

  # Check status
  check_reroute_status "/home/user/nwp/mysite"

Environment Variables:
  REROUTE_DEFAULT_EMAIL  Default reroute address (dev@nwpcode.org)
  REROUTE_WHITELIST      Default whitelist patterns (*@nwpcode.org)
EOF
fi
