#!/usr/bin/env bats
#
# pl clip pairs — the import guards (nwp/ops#358)
#
# The 609 contested pairs are the evaluation corpus the clip programme has been
# missing: 609 places where two retrieval methods disagreed and the machine's
# tiebreak then FAILED adversarial verification, so a human decides. Every rate
# anyone computes from author choices uses 609 as its denominator.
#
# This file gates the two checks that keep that denominator honest, and it
# gates them SEPARATELY, because the obvious objection — "sha256 already
# detects truncation" — is wrong in the case that actually happens:
#
#   * truncated IN TRANSIT      -> the hash catches it
#   * truncated and RE-HASHED   -> the hash is perfect and 209 pairs are gone
#
# The second is a partial export, a run that died at row 400, or a sidecar
# regenerated by a well-meaning script. Only the row count sees it. ops#357 is
# the same defect one layer up: a serialiser truncated at 6,000 characters in
# silence and the applier read the absence of a verdict as a pass.

setup() {
    CLIP="${BATS_TEST_DIRNAME}/../../scripts/commands/clip.sh"
    WORK="$(mktemp -d)"
    ART="${WORK}/contested-pairs.jsonl"

    # A synthetic artefact shaped like the real one. 609 rows, one JSON object
    # per line, with the fields the pair UI actually reads.
    : > "$ART"
    for i in $(seq 1 609); do
        printf '{"lp_id":"A1.%03d","kept":{"moment_id":"m%d","passage_id":"r-e0375-364","start":364.1,"end":690.06,"duration_s":326.0,"agreeing_sources":["rubric"]},"alternate":{"moment_id":"a%d","passage_id":"g45-e0418-s00182","start":902.02,"end":942.44,"duration_s":40.42,"agreeing_sources":["dense","lex"]},"which_is_in_shortlist":"deep","note":"two methods disagreed"}\n' "$i" "$i" "$i" >> "$ART"
    done
    _reseal
}

teardown() {
    rm -rf "$WORK"
}

# Write a sidecar that matches the artefact as it currently stands.
_reseal() {
    ( cd "$WORK" && sha256sum "contested-pairs.jsonl" > "contested-pairs.jsonl.sha256" )
}

@test "a whole, correctly-sealed artefact VERIFIES" {
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 0 ]
    [[ "$output" == *"sha256 verified"* ]]
    [[ "$output" == *"row count verified: 609 pairs"* ]]
    [[ "$output" == *"Artefact is whole"* ]]
}

# ── The hash ────────────────────────────────────────────────────────────────

@test "a corrupted artefact is REFUSED on the sha256" {
    # One byte, in the middle. The classic transit corruption.
    printf 'x' | dd of="$ART" bs=1 seek=200 conv=notrunc status=none
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"sha256 MISMATCH"* ]]
    [[ "$output" == *"Nothing imported"* ]]
}

@test "the refusal names BOTH hashes, so the operator can tell which file is wrong" {
    printf 'x' | dd of="$ART" bs=1 seek=200 conv=notrunc status=none
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"expected:"* ]]
    [[ "$output" == *"actual:"* ]]
}

@test "a MISSING sidecar fails closed — unverified bytes are not imported" {
    rm -f "${ART}.sha256"
    run "$CLIP" pairs verify --file="$ART"
    # 2 = CANNOT VERIFY, never 0.
    [ "$status" -eq 2 ]
    [[ "$output" == *"refusing to import unverified bytes"* ]] || \
    [[ "$output" == *"No sidecar"* ]]
}

@test "an EMPTY sidecar is not a pass" {
    : > "${ART}.sha256"
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 2 ]
    [[ "$output" == *"declares no hash"* ]]
}

# ── The count: the check the hash cannot make ───────────────────────────────

@test "THE CASE THAT MATTERS: truncated and re-sealed is still REFUSED" {
    # Cut 209 rows, then regenerate the sidecar over the truncated file —
    # exactly what a partial export followed by `sha256sum >` produces.
    head -400 "$ART" > "${ART}.tmp" && mv "${ART}.tmp" "$ART"
    _reseal

    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    # The hash must PASS here — otherwise this test is accidentally the
    # previous one and proves nothing about the count.
    [[ "$output" == *"sha256 verified"* ]]
    [[ "$output" == *"Row count MISMATCH"* ]]
    [[ "$output" == *"expected 609, found 400"* ]]
    [[ "$output" == *"Nothing imported"* ]]
}

@test "the refusal explains WHY the count is checked separately" {
    head -400 "$ART" > "${ART}.tmp" && mv "${ART}.tmp" "$ART"
    _reseal
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"hash can be regenerated over a truncated file"* ]]
}

# A mid-line truncation keeps the LINE COUNT intact — the final line is simply
# shorter — so the count check cannot see it. The signature is the missing
# final newline. This test caught the verb accepting exactly this on its first
# run, and the missing-newline guard was added because of it.
@test "truncated MID-LINE and re-sealed is refused" {
    truncate -s -60 "$ART"
    _reseal
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"TRUNCATED MID-LINE"* ]]
    [[ "$output" == *"Nothing imported"* ]]
    # The hash must PASS, or this test is silently a duplicate of the sha case.
    [[ "$output" == *"sha256 verified"* ]]
}

@test "an artefact with one row too MANY is refused" {
    tail -1 "$ART" >> "$ART"
    _reseal
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"expected 609, found 610"* ]]
}

@test "an EMPTY artefact is refused, not reported as zero work done" {
    : > "$ART"
    _reseal
    run "$CLIP" pairs verify --file="$ART"
    [ "$status" -eq 1 ]
    [[ "$output" == *"Row count MISMATCH"* ]]
    [[ "$output" == *"found 0"* ]]
}

@test "--expected-rows is honoured, so a future artefact is not stuck at 609" {
    head -400 "$ART" > "${ART}.tmp" && mv "${ART}.tmp" "$ART"
    _reseal
    run "$CLIP" pairs verify --file="$ART" --expected-rows=400
    [ "$status" -eq 0 ]
    [[ "$output" == *"row count verified: 400 pairs"* ]]
}

# ── Refusing before the site is touched ─────────────────────────────────────

@test "import REFUSES a bad artefact without needing a site to exist" {
    printf 'x' | dd of="$ART" bs=1 seek=200 conv=notrunc status=none
    run "$CLIP" pairs import nwc --file="$ART" --apply
    [ "$status" -ne 0 ]
    [[ "$output" == *"MISMATCH"* ]]
    # The staging drop must NOT have been written: verification happens first.
    [ ! -f "${BATS_TEST_DIRNAME}/../../sites/nwc/dev/.nwp-import/contested-pairs.jsonl" ] || \
      [[ "$(sha256sum < "${BATS_TEST_DIRNAME}/../../sites/nwc/dev/.nwp-import/contested-pairs.jsonl")" != "$(sha256sum < "$ART")" ]]
}

@test "import without a site name refuses rather than guessing one" {
    run "$CLIP" pairs import --file="$ART"
    [ "$status" -eq 2 ]
    [[ "$output" == *"Which site"* ]]
}

@test "an unknown site/tier is refused" {
    run "$CLIP" pairs import no-such-site-xyz --file="$ART"
    [ "$status" -eq 2 ]
    [[ "$output" == *"No such site/tier"* ]]
}

@test "a non-existent artefact file is CANNOT VERIFY, not a pass" {
    run "$CLIP" pairs verify --file="${WORK}/nope.jsonl"
    [ "$status" -eq 2 ]
    [[ "$output" == *"Not a readable file"* ]]
}

@test "dry run is the DEFAULT — --apply is required to store" {
    run "$CLIP" pairs import --help
    [ "$status" -eq 0 ]
    [[ "$output" == *"Without it this is a DRY RUN"* ]]
}

@test "an unknown subcommand refuses rather than doing something surprising" {
    run "$CLIP" pairs frobnicate
    [ "$status" -eq 2 ]
    [[ "$output" == *"Unknown"* ]]
}

# The build host may not be hard-coded: nwp/nwp is publicly mirrored and the
# gitleaks ruleset bans internal host names in tracked files — it refused this
# verb when the host was a literal. So the host is supplied, and its ABSENCE
# must refuse rather than fetch from somewhere surprising.
@test "fetching with no build host refuses instead of guessing" {
    NWP_CLIP_PAIRS_HOST="" run "$CLIP" pairs verify
    [ "$status" -eq 2 ]
    [[ "$output" == *"No build host"* ]]
}

@test "the verb contains no hard-coded internal host name" {
    run grep -nE '(^|[^A-Za-z0-9_])(mini|met|mons)([^A-Za-z0-9_]|$)' "$CLIP"
    [ "$status" -ne 0 ]
}
