#!/bin/sh
# certbot deploy hook: reload GitLab's bundled nginx after a cert renews.
#
# On this box the running web server is GitLab's runit-managed nginx
# (/opt/gitlab/embedded/sbin/nginx), NOT the system nginx.service (which is
# disabled). certbot renews certs under /etc/letsencrypt/live/ but cannot know
# to reload GitLab nginx, so renewed certs would otherwise not be picked up
# until the next manual reload. This hook closes that gap for ALL certs.
#
# Deploy hooks run once per renewed lineage, only on actual renewal.
set -e
logger -t certbot-deploy "reloading GitLab nginx after renewal of ${RENEWED_LINEAGE:-unknown}"
/opt/gitlab/bin/gitlab-ctl hup nginx
